### ISSUE TITLE
Conversion of units

### ISSUE THREAD

**Issue by anthonyverghese** [AguaClara/aide_document#13]
Some units in the json files are not what we want to go with. We should have a way to convert values if we want to change the units in the final json. In addition, we have to figure out how to convert values based on conventions in different countries.

**Comment by ethan92429** [comment]
I don't think we should do anything with this for a long time, if ever. Assume the units are the ones you want. And assume they are given as a single string with units built in. This is too complex and opinionated to embark on and I'm not sure it's necessary, because we have a different way to change the units.
